image:
  repository: geo2face/complete-devops-project
  tag: c31d2c8
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enable: false
autoscaling:
  enabled: false