image:
  repository: geo2face/devops-project
  tag: be1c461
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enable: false
autoscaling:
  enabled: false